### ISSUE TITLE
containers from scratch: `--mount-proc` doesn't work

### ISSUE THREAD

**Issue by raylu** [ericchiang/ericchiang.github.io#2]
https://ericchiang.github.io/post/containers-from-scratch/ says to use `--mount-proc=$PWD/rootfs/proc` but that doesn't work because of https://github.com/karelzak/util-linux/issues/648

**Comment by rhdojun** [comment]
Running into the same issue on RHEL8CSB. Please update the post, Eric.

**Comment by rhdojun** [comment]
Also worth reading in this regard: https://unix.stackexchange.com/a/535581

**Comment by rhdojun** [comment]
I played around a little more. Mounting proc manually inside the container is not good. If done incorrectly (which I did, and I don't know what my mistake was) you lose the global proc and can't even remount it.

What helps is adding the `--fork` flag. Not sure why yet, but someone tries to explain it here more in-depth: https://bugzilla.redhat.com/show_bug.cgi?id=1390057
